[project]
name = "realcolor"
version = "0.2.0"
description = "Simulate colorblindness in Python charts"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Joseph Barbier", email = "joseph@ysunflower.com" },
]
keywords = ["colorblind", "colors", "deuteranomaly", "matplotlib", "plotnine", "protanomaly", "seaborn", "tritanomaly"]
classifiers = ["Development Status :: 4 - Beta", "Operating System :: OS Independent", "Programming Language :: Python :: 3"]
dependencies = [
  "colorspacious>=1.1.2",
  "matplotlib",
]

[project.urls]
Documentation = "https://github.com/y-sunflower/realcolor/"
Homepage = "https://github.com/y-sunflower/realcolor/"
Issues = "https://github.com/y-sunflower/realcolor/issues"
Repository = "https://github.com/y-sunflower/realcolor"

[dependency-groups]
dev = [
  "plotnine[extra]",
  "pre-commit>=4.2.0",
  "pytest>=8.3.5",
  "ruff>=0.11.13",
  "ty>=0.0.15",
]

[build-system]
requires = [
  "setuptools",
  "setuptools-scm",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["realcolor"]

[tool.uv.sources]
realcolor = { workspace = true }
